services:
  surfshark:
    image: myimage
    container_name: surfshark
    environment:
      - SURFSHARK_USER=wn2AVRVKpE3hjdShYwAK8pcS
      - SURFSHARK_PASSWORD=ZrdaUQ5AKjuwE4vMVfWYYdyq
      - LOCAL_NETWORK=192.168.1.0/24,10.1.1.0/24,172.20.0.0/24
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.eth0.route_localnet=1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8118:8118 # http proxy
      - 1080:1080 # socks5 proxy
    networks:
      - default
    dns:
      - 1.1.1.1
# docker run -d --name surfshark1 --cap-add NET_ADMIN --device /dev/net/tun --sysctl net.ipv6.conf.all.disable_ipv6=1 --sysctl net.ipv4.conf.eth0.route_localnet=1 -e SURFSHARK_USER=wn2AVRVKpE3hjdShYwAK8pcS -e SURFSHARK_PASSWORD=ZrdaUQ5AKjuwE4vMVfWYYdyq -e LOCAL_NETWORK=192.168.1.0/24,10.1.1.0/24,172.20.0.0/24 -p 8111:8118 -p 1081:1080 --dns 1.1.1.1 myimage
